services:
  campusenroll-redis-haproxy:
    image: haproxy:2.9-alpine
    container_name: campusenroll-redis-haproxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./haproxy/redis-ha.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
