services:
  campusenroll-postgres:
    image: postgres:16
    container_name: campusenroll-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: campus
      POSTGRES_PASSWORD: campus123
      POSTGRES_DB: campusenroll
    ports:
      - "55432:5432"
    volumes:
      - campusenroll_pg_data:/var/lib/postgresql/data
    networks:
      - campusenroll-net

  campusenroll-flyway:
    image: flyway/flyway:10
    container_name: campusenroll-flyway
    profiles:
      - db-migration
    command:
      - -url=jdbc:postgresql://campusenroll-postgres:5432/campusenroll
      - -user=campus
      - -password=campus123
      - -schemas=campusenroll
      - -connectRetries=30
      - migrate
    volumes:
      - ./database/migrations:/flyway/sql:ro
    depends_on:
      - campusenroll-postgres
    networks:
      - campusenroll-net

  campusenroll-redis:
    image: redis:7
    container_name: campusenroll-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - campusenroll-net

  campusenroll-rabbitmq:
    image: rabbitmq:3-management
    container_name: campusenroll-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: campus
      RABBITMQ_DEFAULT_PASS: campus123
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - campusenroll-net

  campusenroll-prometheus:
    image: prom/prometheus
    container_name: campusenroll-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - campusenroll-net

  campusenroll-grafana:
    image: grafana/grafana
    container_name: campusenroll-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - campusenroll-net

  k6:
    image: grafana/k6
    container_name: campusenroll-k6
    profiles:
      - testing
    volumes:
      - ./tests:/scripts
    networks:
      - campusenroll-net

  billing-service:
    build:
      context: ../billing-service
      dockerfile: Dockerfile
    container_name: campusenroll-billing-service
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://campusenroll-postgres:5432/campusenroll
      SPRING_DATASOURCE_USERNAME: campus
      SPRING_DATASOURCE_PASSWORD: campus123
      SPRING_RABBITMQ_HOST: campusenroll-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: campus
      SPRING_RABBITMQ_PASSWORD: campus123
      SPRING_REDIS_HOST: campusenroll-redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8083:8083"
    depends_on:
      campusenroll-postgres:
        condition: service_started
      campusenroll-redis:
        condition: service_started
      campusenroll-rabbitmq:
        condition: service_started
    networks:
      - campusenroll-net

  notification-service:
    build:
      context: ../notification
      dockerfile: Dockerfile
    container_name: campusenroll-notification-service
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://campusenroll-postgres:5432/campusenroll
      SPRING_DATASOURCE_USERNAME: campus
      SPRING_DATASOURCE_PASSWORD: campus123
      SPRING_RABBITMQ_HOST: campusenroll-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: campus
      SPRING_RABBITMQ_PASSWORD: campus123
      SPRING_REDIS_HOST: campusenroll-redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8084:8084"
    depends_on:
      campusenroll-postgres:
        condition: service_started
      campusenroll-redis:
        condition: service_started
      campusenroll-rabbitmq:
        condition: service_started
    networks:
      - campusenroll-net

  student-service:
    profiles:
      - future
    build:
      context: ../student-service
      dockerfile: Dockerfile
    container_name: campusenroll-student-service
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://campusenroll-postgres:5432/campusenroll
      SPRING_DATASOURCE_USERNAME: campus
      SPRING_DATASOURCE_PASSWORD: campus123
    ports:
      - "8081:8081"
    depends_on:
      campusenroll-postgres:
        condition: service_started
    networks:
      - campusenroll-net

  course-service:
    profiles:
      - future
    build:
      context: ../course-service
      dockerfile: Dockerfile
    container_name: campusenroll-course-service
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://campusenroll-postgres:5432/campusenroll
      SPRING_DATASOURCE_USERNAME: campus
      SPRING_DATASOURCE_PASSWORD: campus123
    ports:
      - "8082:8082"
    depends_on:
      campusenroll-postgres:
        condition: service_started
    networks:
      - campusenroll-net

  enrollment-service:
    profiles:
      - future
    build:
      context: ../enrollment-service/enrollment-service/enrollment-service
      dockerfile: Dockerfile
    container_name: campusenroll-enrollment-service
    restart: unless-stopped
    environment:
      SERVER_PORT: 8085
      SPRING_DATASOURCE_URL: jdbc:postgresql://campusenroll-postgres:5432/campusenroll
      SPRING_DATASOURCE_USERNAME: campus
      SPRING_DATASOURCE_PASSWORD: campus123
      SPRING_RABBITMQ_HOST: campusenroll-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: campus
      SPRING_RABBITMQ_PASSWORD: campus123
      STUDENT_SERVICE_URL: http://student-service:8081
      COURSE_SERVICE_URL: http://course-service:8082
      BILLING_SERVICE_URL: http://billing-service:8083
    ports:
      - "8085:8085"
    depends_on:
      campusenroll-postgres:
        condition: service_started
      campusenroll-rabbitmq:
        condition: service_started
      student-service:
        condition: service_started
      course-service:
        condition: service_started
      billing-service:
        condition: service_started
    networks:
      - campusenroll-net

volumes:
  campusenroll_pg_data:

networks:
  campusenroll-net:
    driver: bridge
