global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["campusenroll-prometheus:9090"]

  - job_name: "billing-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["billing-service:8083"]

  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["notification-service:8084"]

  # These targets are expected to be UP when the future profile is enabled.
  - job_name: "student-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["student-service:8081"]

  - job_name: "course-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["course-service:8082"]

  # enrollment-service is expected to be UP when the future profile is enabled.
  - job_name: "enrollment-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["enrollment-service:8085"]
