listeners.tcp.default = 5672
management.tcp.port = 15672

cluster_name = campusenroll-rabbitmq-ha
cluster_partition_handling = pause_minority

cluster_formation.peer_discovery_backend = classic_config
cluster_formation.classic_config.nodes.1 = rabbit@rabbitmq-jared
cluster_formation.classic_config.nodes.2 = rabbit@rabbitmq-mefi
cluster_formation.classic_config.nodes.3 = rabbit@rabbitmq-brayan

default_queue_type = quorum
queue_master_locator = min-masters

loopback_users.guest = false

