$ErrorActionPreference = "Stop"

param(
    [string]$OutputPath = ".\\api-gateway\\nginx.lan.generated.conf"
)

function Parse-Upstreams {
    param([string]$Raw)
    if ([string]::IsNullOrWhiteSpace($Raw)) { return @() }
    return ($Raw -split "," | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" })
}

function Render-Upstream {
    param(
        [string]$Name,
        [string]$EnvVarName,
        [string[]]$Servers
    )

    if ($Servers.Count -lt 1) {
        throw "Missing upstream servers for $Name. Set $EnvVarName like '192.168.1.30:8081,192.168.1.31:8081'."
    }

    $lines = @()
    $lines += "  upstream $Name {"
    for ($i = 0; $i -lt $Servers.Count; $i++) {
        $server = $Servers[$i]
        $suffix = ""
        if ($i -eq ($Servers.Count - 1) -and $Servers.Count -gt 1) { $suffix = " backup" }
        $lines += "    server $server max_fails=2 fail_timeout=10s$suffix;"
    }
    $lines += "  }"
    return ($lines -join "`n")
}

$student = Parse-Upstreams $env:STUDENT_SERVICE_UPSTREAMS
$course = Parse-Upstreams $env:COURSE_SERVICE_UPSTREAMS
$billing = Parse-Upstreams $env:BILLING_SERVICE_UPSTREAMS
$notification = Parse-Upstreams $env:NOTIFICATION_SERVICE_UPSTREAMS
$enrollment = Parse-Upstreams $env:ENROLLMENT_SERVICE_UPSTREAMS

$upstreams = @(
    (Render-Upstream -Name "student_service" -EnvVarName "STUDENT_SERVICE_UPSTREAMS" -Servers $student),
    "",
    (Render-Upstream -Name "course_service" -EnvVarName "COURSE_SERVICE_UPSTREAMS" -Servers $course),
    "",
    (Render-Upstream -Name "billing_service" -EnvVarName "BILLING_SERVICE_UPSTREAMS" -Servers $billing),
    "",
    (Render-Upstream -Name "notification_service" -EnvVarName "NOTIFICATION_SERVICE_UPSTREAMS" -Servers $notification),
    "",
    (Render-Upstream -Name "enrollment_service" -EnvVarName "ENROLLMENT_SERVICE_UPSTREAMS" -Servers $enrollment)
) -join "`n"

$config = @"
# Generated by scripts/gateway-generate-nginx-lan.ps1.
# This is a LAN lab/demo configuration (not production HA).
# Nginx OSS uses passive failover (no active upstream health checks).

events {}

http {
  log_format campusenroll '`$remote_addr - `$request_method `$uri '
                          'host=`$host request_id=`$request_id status=`$status '
                          'request_time=`$request_time upstream_addr=`$upstream_addr '
                          'upstream_status=`$upstream_status upstream_response_time=`$upstream_response_time';

  proxy_connect_timeout 3s;
  proxy_send_timeout 15s;
  proxy_read_timeout 15s;
  proxy_next_upstream error timeout http_502 http_503 http_504;
  proxy_next_upstream_tries 2;

$upstreams

  server {
    listen 8080;
    server_name _;

    add_header X-Gateway "campusenroll-nginx-lan" always;
    access_log /var/log/nginx/access.log campusenroll;

    proxy_http_version 1.1;
    proxy_set_header Host `$host;
    proxy_set_header X-Real-IP `$remote_addr;
    proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto `$scheme;
    proxy_set_header X-Request-ID `$request_id;

    location = /health {
      access_log off;
      default_type application/json;
      return 200 '{"status":"UP","service":"api-gateway","mode":"lan-generated"}';
    }

    location = /nginx_status {
      stub_status;
      access_log off;
    }

    location = /health/student-service { access_log off; proxy_pass http://student_service/actuator/health; }
    location = /health/course-service { access_log off; proxy_pass http://course_service/actuator/health; }
    location = /health/billing-service { access_log off; proxy_pass http://billing_service/actuator/health; }
    location = /health/notification-service { access_log off; proxy_pass http://notification_service/actuator/health; }
    location = /health/enrollment-service { access_log off; proxy_pass http://enrollment_service/actuator/health; }

    location = /students { proxy_pass http://student_service/students; }

    location ~ ^/students/[^/]+/notifications/?$ {
      proxy_pass http://notification_service;
      proxy_http_version 1.1;
      proxy_set_header Host `$host;
      proxy_set_header X-Real-IP `$remote_addr;
      proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto `$scheme;
    }

    location /students/ {
      proxy_pass http://student_service;
      proxy_http_version 1.1;
      proxy_set_header Host `$host;
      proxy_set_header X-Real-IP `$remote_addr;
      proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto `$scheme;
    }

    location = /api/students {
      proxy_pass http://student_service/api/students;
      proxy_http_version 1.1;
      proxy_set_header Host `$host;
      proxy_set_header X-Real-IP `$remote_addr;
      proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto `$scheme;
    }

    location /api/students/ {
      proxy_pass http://student_service;
      proxy_http_version 1.1;
      proxy_set_header Host `$host;
      proxy_set_header X-Real-IP `$remote_addr;
      proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto `$scheme;
    }

    location = /courses {
      proxy_pass http://course_service/courses;
      proxy_http_version 1.1;
      proxy_set_header Host `$host;
      proxy_set_header X-Real-IP `$remote_addr;
      proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto `$scheme;
    }

    location /courses/ {
      proxy_pass http://course_service;
      proxy_http_version 1.1;
      proxy_set_header Host `$host;
      proxy_set_header X-Real-IP `$remote_addr;
      proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto `$scheme;
    }

    location = /sections {
      proxy_pass http://course_service/sections;
      proxy_http_version 1.1;
      proxy_set_header Host `$host;
      proxy_set_header X-Real-IP `$remote_addr;
      proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto `$scheme;
    }

    location /sections/ {
      proxy_pass http://course_service;
      proxy_http_version 1.1;
      proxy_set_header Host `$host;
      proxy_set_header X-Real-IP `$remote_addr;
      proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto `$scheme;
    }

    location = /payments {
      proxy_pass http://billing_service/payments;
      proxy_http_version 1.1;
      proxy_set_header Host `$host;
      proxy_set_header X-Real-IP `$remote_addr;
      proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto `$scheme;
    }

    location /payments/ {
      proxy_pass http://billing_service;
      proxy_http_version 1.1;
      proxy_set_header Host `$host;
      proxy_set_header X-Real-IP `$remote_addr;
      proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto `$scheme;
    }

    location = /notifications {
      proxy_pass http://notification_service/notifications;
      proxy_http_version 1.1;
      proxy_set_header Host `$host;
      proxy_set_header X-Real-IP `$remote_addr;
      proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto `$scheme;
    }

    location /notifications/ {
      proxy_pass http://notification_service;
      proxy_http_version 1.1;
      proxy_set_header Host `$host;
      proxy_set_header X-Real-IP `$remote_addr;
      proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto `$scheme;
    }

    location = /api/enrollments {
      proxy_pass http://enrollment_service/api/enrollments;
      proxy_http_version 1.1;
      proxy_set_header Host `$host;
      proxy_set_header X-Real-IP `$remote_addr;
      proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto `$scheme;
    }

    location /api/enrollments/ {
      proxy_pass http://enrollment_service;
      proxy_http_version 1.1;
      proxy_set_header Host `$host;
      proxy_set_header X-Real-IP `$remote_addr;
      proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto `$scheme;
    }

    location ~ ^/api/students/[^/]+/enrollments/?$ {
      proxy_pass http://enrollment_service;
      proxy_http_version 1.1;
      proxy_set_header Host `$host;
      proxy_set_header X-Real-IP `$remote_addr;
      proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto `$scheme;
    }
  }
}
"@

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputPath) | Out-Null
Set-Content -LiteralPath $OutputPath -Value $config -Encoding UTF8

Write-Host "Generated LAN Nginx config at: $OutputPath"
Write-Host "To use it: set GATEWAY_NGINX_CONF=$OutputPath and run docker compose (gateway stack)."
