bind 0.0.0.0
protected-mode no
port 26379
dir /data

sentinel monitor campusenroll-redis 192.168.0.12 6379 2
sentinel down-after-milliseconds campusenroll-redis 5000
sentinel failover-timeout campusenroll-redis 60000
sentinel parallel-syncs campusenroll-redis 1
sentinel announce-ip 192.168.0.10
sentinel announce-port 26379
